# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('manage_project', models.IntegerField()),
                ('presonal_information', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('accept_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('project_publisher', models.CharField(max_length=30)),
                ('project_content', models.TextField()),
                ('project_receiver', models.CharField(max_length=30)),
                ('project_manager', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('order_project', models.IntegerField()),
                ('presonal_information', models.CharField(max_length=100)),
                ('accept_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('get_project', models.IntegerField()),
                ('presonal_information', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('accept_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('identity', models.CharField(max_length=15)),
            ],
        ),
    ]
