# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('manage_project', models.IntegerField()),
                ('presonal_information', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('accept_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('project_publisher', models.CharField(max_length=30)),
                ('project_content', models.TextField()),
                ('project_receiver', models.CharField(max_length=30)),
                ('project_manager', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('order_project', models.IntegerField()),
                ('presonal_information', models.CharField(max_length=100)),
                ('accept_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('get_project', models.IntegerField()),
                ('presonal_information', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('accept_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
