# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_market', '0002_project_need_receiver_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='hehe', max_length=50),
            preserve_default=False,
        ),
    ]
