# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_market', '0003_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_receiver',
            field=models.CharField(max_length=100),
        ),
    ]
