# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_market', '0004_auto_20161103_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='number',
        ),
    ]
