# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_market', '0006_auto_20161103_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manage_project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='order_project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='get_project',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
